services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    buildCommand: ./render/build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
